# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sentei < Formula
  desc "A TUI tool for cleaning up stale git worktrees"
  homepage "https://github.com/abiswas97/sentei"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abiswas97/sentei/releases/download/v1.0.0/sentei_1.0.0_darwin_amd64.tar.gz"
      sha256 "81a6cbaec96aa70eb291b985f5e1638a7473c66fb9b42ee4f8e4b8116003f215"

      def install
        bin.install "sentei"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abiswas97/sentei/releases/download/v1.0.0/sentei_1.0.0_darwin_arm64.tar.gz"
      sha256 "df04705b6d8dc6a6466b3632beb6f74aacb4b7338245206537ab8f112472a015"

      def install
        bin.install "sentei"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abiswas97/sentei/releases/download/v1.0.0/sentei_1.0.0_linux_amd64.tar.gz"
      sha256 "79439672dc71627efe814b8577c03d3ced6622ce6f4449f683aa76d0c9df16aa"
      def install
        bin.install "sentei"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abiswas97/sentei/releases/download/v1.0.0/sentei_1.0.0_linux_arm64.tar.gz"
      sha256 "70c278f7251b037a6ee3103e73ed6b559befd4b88035e0a413b033bf0dbdb7bf"
      def install
        bin.install "sentei"
      end
    end
  end
end
