# This file was generated by GoReleaser. DO NOT EDIT.
cask "sentei" do
  name "sentei"
  desc "A TUI tool for cleaning up stale git worktrees"
  homepage "https://github.com/abiswas97/sentei"
  version "0.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sentei"

  on_macos do
    on_intel do
      url "https://github.com/abiswas97/sentei/releases/download/v#{version}/sentei_#{version}_darwin_amd64.tar.gz"
      sha256 "4a43a5d047a584b744e0e195d8f259500c381acac74bfa672ed1123917ef53ec"
    end
    on_arm do
      url "https://github.com/abiswas97/sentei/releases/download/v#{version}/sentei_#{version}_darwin_arm64.tar.gz"
      sha256 "1ee9183d134b9d44bd9f64f210ff3403b2ad073132079d3cc0828e0b8e126ac5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abiswas97/sentei/releases/download/v#{version}/sentei_#{version}_linux_amd64.tar.gz"
      sha256 "089b6734d405ae718b7972f99b069cdf3419f15d9e83a06464b2e2a758732a19"
    end
    on_arm do
      url "https://github.com/abiswas97/sentei/releases/download/v#{version}/sentei_#{version}_linux_arm64.tar.gz"
      sha256 "6dda22c3e01384434c31cb5af8df309ea4efb20451f04f816f85ae19008cdfd7"
    end
  end

  # No zap stanza required
end
